Num_avg = input("please enter 5 numbers: ")
num_1 = float(input())
num_2 = float(input())
num_3 = float(input())
num_4 = float(input())
num_5 = float(input())
add_all = (num_1 + num_2 + num_3 + num_4 + num_5)
average_1 = (add_all / 5)
print(f"the average is:", average_1)